# ============================================================
#  setup_new_host.ps1 - guided setup for moving the ArchViz
#  pixel-streaming host to a new dedicated machine.
#
#  Run this ON the new machine, from inside a fresh clone of
#  this repo (archviz-launcher-infra). It handles everything that
#  can safely be automated; anything that touches secrets or the
#  multi-GB UE5 build is printed as a manual checklist instead of
#  guessed at.
# ============================================================

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot

function Section($title) {
    Write-Host ""
    Write-Host "== $title ==" -ForegroundColor Cyan
}

function Ok($msg)   { Write-Host "  [OK] $msg" -ForegroundColor Green }
function Warn($msg) { Write-Host "  [!!] $msg" -ForegroundColor Yellow }
function Info($msg) { Write-Host "  $msg" }

Write-Host "ArchViz Host Setup" -ForegroundColor Magenta
Write-Host "===================="
Write-Host "Install root: $root"

# ---------------------------------------------------------------
Section "Prerequisite checks"

try {
    $nodeVersion = node --version
    Ok "Node.js found ($nodeVersion)"
} catch {
    Warn "Node.js not found on PATH. Install it from https://nodejs.org before continuing."
}

# ---------------------------------------------------------------
Section "Machine-specific paths (host.config)"

Info "These get written to host.config - the one file every script here reads"
Info "for machine-specific paths, instead of hardcoding them per-script."
Write-Host ""

$hostName = Read-Host "Host machine name (e.g. `"Erick's GPU Rig`")"
if ([string]::IsNullOrWhiteSpace($hostName)) { $hostName = $env:COMPUTERNAME }

$ue5Exe = Read-Host "Full path to the packaged UE5 .exe (e.g. C:\ArchViz\Build\ArchVizProject3.exe)"
if (-not (Test-Path $ue5Exe)) {
    Warn "That path doesn't exist yet - that's fine if the build hasn't been copied over yet, just make sure host.config points at the right place once it is."
}

$signalDir = Read-Host "Full path to the SignallingWebServer folder (inside <UE5 Engine>\Engine\Plugins\Media\PixelStreaming\Resources\WebServers\SignallingWebServer)"
if (-not (Test-Path (Join-Path $signalDir "platform_scripts\cmd\start.bat"))) {
    Warn "start.bat not found under that path - double-check the UE5 Engine install has the PixelStreaming plugin before relying on this path."
}

$hostConfigContent = @"
; ============================================================
;  host.config - machine-specific settings for whichever computer
;  is currently running the ArchViz stream.
;
;  Read by launch_pixelstream.bat, start_wilbur.bat, and
;  launcher-server.js - change values here instead of hunting
;  through each script when this ever needs to run on a different
;  machine. Generated by setup_new_host.ps1 on $(Get-Date -Format 'yyyy-MM-dd').
; ============================================================
HOST_NAME=$hostName
UE5_EXE=$ue5Exe
SIGNAL_DIR=$signalDir
"@
Set-Content -Path (Join-Path $root "host.config") -Value $hostConfigContent -Encoding ASCII
Ok "host.config written"

# ---------------------------------------------------------------
Section "Cloudflare Tunnel binary"

$cfPath = Join-Path $root "cloudflared.exe"
if (Test-Path $cfPath) {
    Ok "cloudflared.exe already present"
} else {
    Info "Downloading latest cloudflared.exe (this one's gitignored - re-download is the intended way to get it)..."
    try {
        Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile $cfPath -TimeoutSec 60
        Ok "cloudflared.exe downloaded"
    } catch {
        Warn "Download failed ($($_.Exception.Message)) - grab it manually from https://github.com/cloudflare/cloudflared/releases/latest"
    }
}

# ---------------------------------------------------------------
Section "Port availability"

foreach ($port in 3000, 80, 8888, 8889) {
    $inUse = Get-NetTCPConnection -LocalPort $port -State Listen -ErrorAction SilentlyContinue
    if ($inUse) { Warn "Port $port is already in use - something else is bound to it." }
    else { Ok "Port $port is free" }
}

# ---------------------------------------------------------------
Section "Frontend overlay (archviz-ui.js)"

$overlayDir = Join-Path $root "_archviz-ui-overlay"
if (-not (Test-Path $overlayDir)) {
    Info "Cloning the frontend overlay repo for reference..."
    git clone https://github.com/ErickGalvez/archviz-ui-overlay.git $overlayDir 2>&1 | Out-Null
}
if (Test-Path (Join-Path $overlayDir "archviz-ui.js")) {
    Ok "Overlay source ready at $overlayDir\archviz-ui.js"
} else {
    Warn "Couldn't clone archviz-ui-overlay automatically - clone it manually: git clone https://github.com/ErickGalvez/archviz-ui-overlay.git"
}

# ---------------------------------------------------------------
Section "MANUAL STEPS - can't be automated, do these before going live"

Write-Host @"

  1. Packaged UE5 build
     Copy the built game (the PKGV3-style output folder, several GB) to
     wherever you pointed UE5_EXE above. Not something git or this script
     can move - copy it over a network share, drive, or cloud transfer.

  2. TURN credential fetch script (secret, intentionally not in git)
     This repo ships get_cf_turn_creds.ps1.example as a template. Copy it to
     get_cf_turn_creds.ps1 and fill in TURN_KEY_ID / TURN_KEY_API_TOKEN -
     either copy the real values from the old machine, or generate a fresh
     Key ID + API Token in the Cloudflare dashboard (Realtime > TURN Keys).

  3. Auth keys (secret, intentionally not in git) - COPY, DO NOT REGENERATE
     admin.key, qa.key, devconsole.key, and devconsole-github.key must be
     the EXACT SAME files on every host that can serve api.g-741studio.com
     (see step 5 below on why more than one host now can). Each of these
     auto-generates a fresh random value if missing, which is fine for a
     single-host setup but breaks the QA dashboard / Dev Console / admin
     panel the moment a request happens to land on a host with a
     different key than the one the browser has. Copy the four files from
     the other host into this folder - do NOT let this script or a first
     run generate new ones.

  4. Is this a second/standby host, or brand new?
     If archviz-launcher-infra is already running somewhere and this is
     an ADDITIONAL host (not a full replacement), stop and read the
     "Two hosts, one site" section of INSTALL.md before continuing - it
     covers the Cloudflare Worker failover setup that lets a primary and
     standby host coexist safely (never run the SAME Cloudflare Tunnel
     identity on two machines at once - see cloudflare_worker_fallback.js
     for exactly why). If this is a straight one-for-one replacement of
     the only host, skip that and continue below as before.

  5. Cloudflare Tunnel identity (secret, lives outside this repo entirely)
     - Single-host replacement: copy these two files from the OLD
       machine's C:\Users\<user>\.cloudflared\ to the same location here:
         config.yml
         <tunnel-id>.json  (the credentials file config.yml points at)
       This lets the SAME tunnel (and the same api.g-741studio.com /
       stream.g-741studio.com DNS records) just start answering from
       this machine instead - no Cloudflare dashboard changes needed.
     - Second/standby host (see step 4): give THIS host its OWN tunnel
       instead - `cloudflared tunnel login` + `cloudflared tunnel create
       <name>` here, then `cloudflared tunnel route dns <name>
       <role>-internal.g-741studio.com` (role = nh or oh, whichever this
       machine is). Do not point it at the public hostnames directly -
       those now route through the Worker, which is what decides which
       internal hostname gets real traffic.

  6. Frontend overlay drop-in
     Wilbur builds its own www/ folder the first time start.bat runs
     (via SetupFrontend). AFTER that first run, copy archviz-ui.js from
     $overlayDir into <SIGNAL_DIR>\www\archviz-ui.js.

  7. common.bat patch (Epic's vendor file, lives inside the Engine install
     - a fresh UE5 5.7 install gets Epic's stock version with NEITHER of
     our two fixes, and there's no git-clone path that carries this one
     over automatically)
     Copy common.bat.patched from this repo over:
       <SIGNAL_DIR>\platform_scripts\cmd\common.bat
     Fixes included: --turn-user/--turn-pass never consumed their value
     (SHIFT was missing); VPS TURN fallback commented out since that
     server no longer exists.

"@

# ---------------------------------------------------------------
Section "Persistent background tasks (listener + tunnel)"

$doTasks = Read-Host "Register the Scheduled Tasks now, so the listener, tunnel, and repo sync auto-start at logon? (y/n)"
if ($doTasks -eq 'y') {
    $action1 = New-ScheduledTaskAction -Execute "wscript.exe" -Argument "`"$root\run_hidden.vbs`" `"$root\listener_service.bat`""
    $action2 = New-ScheduledTaskAction -Execute "wscript.exe" -Argument "`"$root\run_hidden.vbs`" `"$root\tunnel_service.bat`""
    $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
    $settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit ([TimeSpan]::Zero) -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1) -DontStopIfGoingOnBatteries -AllowStartIfOnBatteries -StartWhenAvailable

    Register-ScheduledTask -TaskName "ArchViz-Listener" -Action $action1 -Trigger $trigger -Settings $settings -Description "Always-on lightweight backend for the ArchViz landing page." -Force | Out-Null
    Register-ScheduledTask -TaskName "ArchViz-Tunnel" -Action $action2 -Trigger $trigger -Settings $settings -Description "Cloudflare tunnel for the ArchViz listener." -Force | Out-Null

    # Keeps this host's code current with origin/main on a timer, independent
    # of whether a Dev Console push happened to be dispatched while THIS
    # host was the one answering requests - see sync_repo.ps1.
    $syncAction = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$root\sync_repo.ps1`""
    $syncTrigger = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes 3) -RepetitionDuration (New-TimeSpan -Days 3650)
    $syncSettings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit (New-TimeSpan -Minutes 2) -DontStopIfGoingOnBatteries -AllowStartIfOnBatteries -StartWhenAvailable
    Register-ScheduledTask -TaskName "ArchViz-Sync" -Action $syncAction -Trigger $syncTrigger -Settings $syncSettings -Description "Keeps this host's archviz-launcher-infra checkout current with origin/main; restarts launcher-server.js if it changes." -Force | Out-Null

    Ok "Scheduled Tasks registered (ArchViz-Listener, ArchViz-Tunnel, ArchViz-Sync). The first two start at your next logon; run 'Start-ScheduledTask -TaskName ArchViz-Listener' (and -Tunnel, -Sync) to start them right now instead of waiting."
} else {
    Info "Skipped. Register later by re-running this script, or manually via Task Scheduler."
}

Section "Done"
Write-Host "Finish the manual steps above, then start the listener and tunnel and check https://api.g-741studio.com/api/status" -ForegroundColor Magenta
